spring:
  application:
    name: hospital
  thymeleaf:
    cache: false

server:
  port: 8080

hospital:
  rdf:
    base-uri: "http://example.org/hospital#"
    storage-path: "data/hospital-tdb2"
  fuseki:
    enabled: true
    port: 3030
    dataset-path: "/hospital"
    allow-update: false
